# Generated by Django 4.2.7 on 2025-12-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_xuatkho_kho_nhan_alter_xuatkho_kho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhapkho',
            name='tong_tien',
        ),
        migrations.RemoveField(
            model_name='xuatkho',
            name='tong_tien',
        ),
    ]
