# Generated by Django 4.2.7 on 2025-12-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_nhapkho_tong_tien_remove_xuatkho_tong_tien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietxuatkho',
            name='don_gia',
        ),
        migrations.RemoveField(
            model_name='chitietxuatkho',
            name='thanh_tien',
        ),
    ]
