# Generated by Django 4.2.7 on 2025-12-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_chitietxuatkho_don_gia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhapkho',
            name='tong_tien',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
