# Generated by Django 4.2.7 on 2025-12-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_sanpham_ton_kho'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='so_luong_toi_thieu',
            field=models.PositiveIntegerField(default=10, help_text='Số lượng tối thiểu trong kho để cảnh báo', verbose_name='Số lượng tối thiểu'),
        ),
    ]
